version: "3.9"

services:
  db:
    # --- Servicio de la Base de Datos (Sin cambios) ---
    image: postgres:17
    container_name: stokly_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: stokly
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stokly"]
      interval: 5s
      retries: 5
      start_period: 10s

  backend:
    image: mmolina07/stokly-backend:v1 
    
    container_name: stokly_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:12345@db:5432/stokly
    ports:
      - "8000:8000"

volumes:
  postgres_data: